### ISSUE TITLE
SSMSPlusSearch: Error parsing column 5 (Scale=0 - Int64)

### ISSUE THREAD

**Issue by patelriki13** [akarzazi/SSMSPlus#8]
Specified cast is not valid.

at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:line 3609
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 468
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SSMSPlusCore.Database.Db.<SelectAsync>d__6`1.MoveNext() in D:\Rikin\Git\SSMSPlus\src\SSMSPlusCore\Db\Db.cs:line 73

**Comment by akarzazi** [comment]
Fixed by @patelriki13 in pull https://github.com/akarzazi/SSMSPlus/pull/9

Version 3.1
